### ISSUE TITLE
More and better documentation

### ISSUE THREAD

**Issue by gaa-cifasis** [CIFASIS/VDiscover#1]

**Comment by xiaoxing521** [comment]
First, Thank you for your open source. But I meet some question when I use VDiscover to detect testcases. 
The command is:
  ~/VDiscover$ fextractor --dynamic /home/xingwenjing/VDiscover/examples/testcases/bc >bc.csv
~/VDiscover$ vpredictor ./bc.csv --dynamic --model /home/xingwenjing/VDiscover/examples/trained-models/model.pklz --out-file predictions.csv
 
And then report wrong message:

Traceback (most recent call last):
  File "/home/xingwenjing/.local/bin/vpredictor", line 4, in <module>
    __import__('pkg_resources').run_script('VDiscover==0.1', 'vpredictor')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/home/xingwenjing/.local/lib/python2.7/site-packages/VDiscover-0.1-py2.7.egg/EGG-INFO/scripts/vpredictor", line 204, in <module>
    test_mode, probability=probability_mode)
  File "/home/xingwenjing/.local/lib/python2.7/site-packages/VDiscover-0.1-py2.7.egg/vdiscover/Recall.py", line 20, in Recall
    model = loadModel(model_file)
  File "/home/xingwenjing/.local/lib/python2.7/site-packages/VDiscover-0.1-py2.7.egg/vdiscover/Utils.py", line 104, in loadModel
    model = pickle.load(gzip.open(model_file))
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1132, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'dynamic_tokenizer'

**Comment by sancica-github** [comment]
I meet the same questions, have you solved it yet?

**Comment by sancicaXX** [comment]
@xiaoxing521 I meet the same questions, have you solved it yet?
